name: CI

on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        node: ['22.0.0']
        platform: [ubuntu-latest]
    name: Node v${{matrix.node}} ((${{matrix.platform}}))
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - name: install dependencies
        run: yarn install
      - name: lint code
        run: yarn lint
      - name: build project
        run: yarn build
      - name: run tests
        run: yarn test
      - name: run tests with coverage
        run: yarn vitest run --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}



